{% set name = "databroker" %}
{% set version = "0.13.3" %}
{% set sha256 = "53c13a7843afeaf34ac9913330afaaaee30f13f869b652e04615772e090c039a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - attrs >=16.3.0
    - boltons
    - cytoolz
    - doct
    - glueviz
    - h5py
    - humanize
    - jinja2
    - jsonschema
    - mongoquery
    - numpy
    - pandas
    - pims
    - pymongo
    - python
    - pytz
    - pyyaml
    - requests
    - six
    - tifffile
    - tornado
    - tzlocal
    - ujson

test:
  imports:
    - databroker
    - databroker.core
    - databroker.broker

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A unified interface to the various data sources at NSLS-II.'
  description: 'A unified interface to the various data sources at NSLS-II.'
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker
