{% set name = "databroker" %}
{% set version = "1.0.5" %}
{% set sha256 = "617add0bee872efdf7368ccdbf9e1a4f6f5526180e2efd11c48a34188f5f4120" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - boltons
    - cachetools
    - dask
    - doct
    - event-model >=1.14.0
    - humanize
    - intake >=0.5.5
    - jinja2
    - jsonschema
    - mongoquery
    - msgpack-numpy
    - msgpack-python
    - numpy
    - pandas
    - pims
    - pymongo
    - pytz
    - pyyaml
    - requests
    - six
    - suitcase-mongo
    - suitcase-msgpack
    - tifffile !=2019.7.26.2
    - toolz
    - tzlocal
    - xarray
    - zarr

test:
  imports:
    - databroker
    - databroker._drivers
    - databroker.assets
    - databroker.assets.readers
    - databroker.assets.tests
    - databroker.eventsource
    - databroker.eventsource.tests
    - databroker.headersource
    - databroker.service
    - databroker.tests
    - databroker.tests.test_v2
  commands:
    - intake drivers list 2>&1 | grep bluesky  # [not win]

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A unified interface to the various data sources at NSLS-II.'
  description: 'A unified interface to the various data sources at NSLS-II.'
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker
