{% set name = "databroker" %}
{% set version = "0.13.2" %}
{% set sha256 = "763e41f4707c27a3d3091d7c0fe9f5c32ef068a280134258bb3af76bfd131d7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest
    - pytest-runner
  run:
    - attrs >=16.3.0
    - boltons
    - cytoolz
    - doct
    - h5py
    - humanize
    - jsonschema
    - jinja2
    - mongoquery
    - numpy
    - pandas
    - pims
    - pymongo
    - python
    - pytz
    - pyyaml
    - requests
    - six
    - tifffile
    - tornado
    - tzlocal
    - ujson

test:
  requires:
    - pytest
  imports:
    - databroker
    - databroker.core
    - databroker.broker
  commands:
    - pytest --pyargs {{ name }}.tests

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A unified interface to the various data sources at NSLS-II.'

  description: 'A unified interface to the various data sources at NSLS-II.'
  doc_url: http://nsls-ii.github.io/databroker/
  dev_url: https://github.com/NSLS-II/databroker/

extra:
  recipe-maintainers:
    - CJ-Wright
    - conda-forge/event-model
