{% set name = "databroker" %}
{% set version = "1.0.0b3" %}
{% set sha256 = "4f846c4901e24538a8478a16d2f18774594821db48806efd481f93498e57b78c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - boltons
    - dask
    - doct
    - event-model >=1.13.0b4
    - humanize
    - intake >=0.5.2
    - jinja2
    - jsonschema
    - mongoquery
    - msgpack-numpy
    - msgpack-python
    - numpy
    - pandas
    - pims
    - pymongo
    - pytz
    - pyyaml
    - requests
    - six
    - suitcase-mongo
    - suitcase-msgpack
    - tifffile
    - toolz
    - tzlocal
    - xarray
    - zarr

test:
  imports:
    - databroker
    - databroker._drivers
    - databroker.assets
    - databroker.assets.readers
    - databroker.assets.tests
    - databroker.eventsource
    - databroker.eventsource.tests
    - databroker.headersource
    - databroker.service
    - databroker.tests
    - databroker.tests.test_v2

about:
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A unified interface to the various data sources at NSLS-II.'
  description: 'A unified interface to the various data sources at NSLS-II.'
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker
